services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
    secrets:
      - db_user_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception-network

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception-network


volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/parmando/data/mariadb
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/parmando/data/wordpress


networks:
  inception-network:
    driver: bridge


secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt